# Generated by Django 5.2.17 on 2026-10-02 09:10

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('admission', 'Tuyển sinh'), ('payment', 'Thanh toán'), ('scheduling', 'Lịch học'), ('marketing', 'Marketing')], default='admission', max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_code', models.CharField(blank=True, max_length=100)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('rendered_html', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Đang gửi'), ('sent', 'Đã gửi'), ('delivered', 'Đã nhận'), ('opened', 'Đã mở'), ('clicked', 'Đã click'), ('bounced', 'Bị dội'), ('complained', 'Báo spam'), ('failed', 'Lỗi'), ('simulated', 'Mô phỏng')], db_index=True, default='queued', max_length=20)),
                ('resend_message_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('last_clicked_url', models.URLField(blank=True, max_length=1000)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('bounce_reason', models.CharField(blank=True, max_length=500)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='crm.order')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svix_id', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='notifications.emaillog')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
