# Generated by Django 5.2.17 on 2026-10-05 06:29

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LmsEnrollment',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ ghi danh'), ('done', 'Đã ghi danh'), ('failed', 'Lỗi – sẽ thử lại'), ('skipped', 'Bỏ qua')], db_index=True, default='pending', max_length=20)),
                ('moodle_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('moodle_course_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user_created', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lms_enrollment', to='crm.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
