# Generated by Django 5.2.17 on 2026-10-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsenrollment',
            name='access_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lmsenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ ghi danh'), ('done', 'Đã ghi danh'), ('failed', 'Lỗi – sẽ thử lại'), ('skipped', 'Bỏ qua'), ('removed', 'Đã hủy ghi danh')], db_index=True, default='pending', max_length=20),
        ),
    ]
