# Generated by Django 5.2.17 on 2026-10-06 02:26

import apps.core.models
import apps.lms.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('lms', '0002_lmsenrollment_access_emailed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsenrollment',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.cohort'),
        ),
        migrations.AddField(
            model_name='lmsenrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lmsenrollment',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lmsenrollment',
            name='progress',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lmsenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ ghi danh'), ('waiting', 'Chờ xếp lớp'), ('done', 'Đã ghi danh'), ('failed', 'Lỗi – sẽ thử lại'), ('skipped', 'Bỏ qua'), ('removed', 'Đã hủy ghi danh')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=apps.lms.models.new_certificate_code, max_length=20, unique=True)),
                ('learner_name', models.CharField(max_length=200)),
                ('course_title', models.CharField(max_length=300)),
                ('cohort_name', models.CharField(blank=True, max_length=200)),
                ('issued_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_reason', models.CharField(blank=True, max_length=300)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='lms.lmsenrollment')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
