# Generated by Django 5.2.17 on 2026-10-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_lmsenrollment_cohort_lmsenrollment_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsenrollment',
            name='attendance_attended',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lmsenrollment',
            name='attendance_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lmsenrollment',
            name='attendance_taken',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lmsenrollment',
            name='certificate_hold',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='lmsenrollment',
            name='grade_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lmsenrollment',
            name='last_access',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lmsenrollment',
            name='risk_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lmsenrollment',
            name='risk_level',
            field=models.CharField(choices=[('ok', 'Ổn'), ('watch', 'Cần theo dõi'), ('risk', 'Có nguy cơ')], db_index=True, default='ok', max_length=10),
        ),
    ]
