# Generated by Django 5.2.17 on 2026-10-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='key',
            field=models.CharField(choices=[('homepage_sections', 'Homepage sections'), ('site_seo', 'Site SEO settings'), ('journeys', 'Automated journey e-mails')], max_length=64, primary_key=True, serialize=False),
        ),
    ]
