# Generated by Django 5.2.17 on 2026-10-02 09:10

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('featured_image', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('published', 'Đã xuất bản'), ('draft', 'Bản nháp'), ('scheduled', 'Hẹn giờ')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('focus_keyword', models.CharField(blank=True, max_length=100)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('seo_score', models.PositiveSmallIntegerField(default=0)),
                ('seo_checks', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.TextField(blank=True)),
                ('bg_gradient', models.CharField(blank=True, max_length=200)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_action', models.CharField(blank=True, max_length=32)),
                ('button_style', models.CharField(default='primary', max_length=16)),
                ('partner_badges', models.JSONField(blank=True, default=list)),
                ('floating_badges', models.JSONField(blank=True, default=list)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('display_type', models.CharField(default='card', max_length=16)),
                ('full_banner_image_url', models.CharField(blank=True, max_length=500)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('target_blank', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
