# Generated by Django 5.2.17 on 2026-10-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_hide_demo_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('path', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=60)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='cms_pagevie_date_0386b5_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'path', 'source'), name='uniq_pageview_day')],
            },
        ),
    ]
