# Generated by Django 5.2.17 on 2026-10-02 09:10

import apps.core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('max_discount_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('min_order_amount', models.PositiveBigIntegerField(default=0)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('max_usage', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('avatar', models.CharField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('credential', models.CharField(blank=True, max_length=300)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('students_count', models.PositiveIntegerField(default=0)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('bank_position', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Đang dạy'), ('on_leave', 'Tạm nghỉ'), ('adjunct', 'Thỉnh giảng')], default='active', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, choices=[('university', 'Trường'), ('company', 'Doanh nghiệp')], max_length=20)),
                ('logo_text', models.CharField(blank=True, max_length=50)),
                ('logo_color', models.CharField(blank=True, max_length=50)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('badge_icon', models.CharField(blank=True, max_length=50)),
                ('slogan', models.CharField(blank=True, max_length=300)),
                ('theme_color', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('delivery_format', models.CharField(blank=True, choices=[('offline', 'Trực tiếp'), ('hybrid', 'Kết hợp'), ('online_external_lms', 'Online qua LMS')], max_length=32)),
                ('location_text', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('career_role', models.CharField(blank=True, max_length=200)),
                ('badge_section', models.CharField(blank=True, max_length=50)),
                ('badge_type', models.CharField(blank=True, max_length=50)),
                ('thumbnail', models.CharField(blank=True, max_length=500)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('enrolled_count', models.CharField(blank=True, max_length=50)),
                ('lessons_count', models.PositiveIntegerField(default=0)),
                ('students_count', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('original_price', models.PositiveBigIntegerField(default=0)),
                ('is_free_enrollment_available', models.BooleanField(default=False)),
                ('youtube_trial_url', models.URLField(blank=True, max_length=500)),
                ('youtube_video_id', models.CharField(blank=True, max_length=32)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('target_audience', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('guarantees', models.JSONField(blank=True, default=list)),
                ('syllabus', models.JSONField(blank=True, default=list)),
                ('reviews', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('instructors', models.ManyToManyField(blank=True, related_name='courses', to='catalog.instructor')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='catalog.partner')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=25)),
                ('status', models.CharField(choices=[('opening', 'Đang tuyển sinh'), ('full', 'Đã đủ sĩ số'), ('in_progress', 'Đang học'), ('completed', 'Đã kết thúc'), ('upcoming', 'Sắp mở')], default='upcoming', max_length=20)),
                ('auto_rollover_waitlist', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('next_cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.cohort')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='catalog.course')),
                ('lead_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.instructor')),
            ],
            options={
                'ordering': ['start_date', 'name'],
                'constraints': [models.UniqueConstraint(fields=('course', 'name'), name='uniq_cohort_name_per_course')],
            },
        ),
    ]
