# Generated by Django 5.2.17 on 2026-10-06 03:49

import apps.core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('installment_interval_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(180)])),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.CharField(blank=True, max_length=500)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('original_price', models.PositiveBigIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='installment_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='course',
            name='installment_interval_days',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.CreateModel(
            name='ProgramCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='catalog.program')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='courses',
            field=models.ManyToManyField(related_name='programs', through='catalog.ProgramCourse', to='catalog.course'),
        ),
        migrations.AddConstraint(
            model_name='programcourse',
            constraint=models.UniqueConstraint(fields=('program', 'course'), name='uniq_program_course'),
        ),
    ]
