# Generated by Django 5.2.17 on 2026-10-06 11:01

from django.db import migrations, models


def status_from_is_published(apps, schema_editor):
    Course = apps.get_model("catalog", "Course")
    for course in Course.objects.filter(is_published=True):
        course.status, course.published_at = "published", course.updated_at
        course.save(update_fields=["status", "published_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_hide_demo_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('review', 'Chờ duyệt'), ('published', 'Đang bán'), ('archived', 'Ngừng bán')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(status_from_is_published, migrations.RunPython.noop),
    ]
