# Generated by Django 5.2.17 on 2026-10-06 11:31

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='calendar_cleanup',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cohort',
            name='early_bird_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='early_bird_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='schedule_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='status',
            field=models.CharField(choices=[('opening', 'Đang tuyển sinh'), ('full', 'Đã đủ sĩ số'), ('closed', 'Đã đóng tuyển sinh'), ('in_progress', 'Đang học'), ('completed', 'Đã kết thúc'), ('upcoming', 'Sắp mở')], default='upcoming', max_length=20),
        ),
        migrations.CreateModel(
            name='CohortSession',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('online', models.BooleanField(default=False)),
                ('moodle_event_id', models.PositiveIntegerField(blank=True, null=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='catalog.cohort')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
    ]
