# Generated by Django 5.2.17 on 2026-10-06 11:38

import apps.core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_intake_pricing_sessions'),
        ('crm', '0003_order_attribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(max_length=2000)),
                ('completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã đăng'), ('rejected', 'Không đăng')], db_index=True, default='pending', max_length=20)),
                ('moderation_note', models.CharField(blank=True, max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_reviews', to='catalog.course')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='crm.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
