# Generated by Django 5.2.17 on 2026-10-07 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_coursereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='attendance_cleanup',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cohort',
            name='moodle_attendance_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohortsession',
            name='moodle_attendance_session_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='min_attendance_rate',
            field=models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
