# Generated by Django 5.2.17 on 2026-10-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receives_leads',
            field=models.BooleanField(default=True),
        ),
    ]
