# Generated by Django 5.2.17 on 2026-10-06 03:49

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


def paid_orders_may_study(apps, schema_editor):
    apps.get_model("crm", "Order").objects.filter(status="paid").update(learning_access=True)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_program_course_installment_count_and_more'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installment_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='learning_access',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='crm.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.program'),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('vietqr', 'VietQR'), ('free', 'Miễn phí'), ('card', 'Thẻ'), ('transfer', 'Chuyển khoản'), ('cash', 'Tiền mặt'), ('bundle', 'Trong gói chương trình')], default='vietqr', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveBigIntegerField()),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='crm.order')),
            ],
            options={
                'ordering': ['order', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('order', 'sequence'), name='uniq_installment_seq')],
            },
        ),
        migrations.RunPython(paid_orders_may_study, migrations.RunPython.noop),
    ]
