# Generated by Django 5.2.17 on 2026-10-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_order_installment_count_order_learning_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attribution',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
