# Generated by Django 5.2.17 on 2026-10-06 11:47

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_order_attribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dossier_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='response_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='terms_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('channel', models.CharField(choices=[('call', 'Gọi điện'), ('zalo', 'Zalo'), ('online', 'Họp online'), ('office', 'Tại văn phòng')], default='call', max_length=20)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Đã hẹn'), ('done', 'Đã tư vấn'), ('no_show', 'Khách không đến'), ('cancelled', 'Đã hủy')], db_index=True, default='planned', max_length=20)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='crm.order')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceRequest',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_type', models.CharField(choices=[('company', 'Công ty'), ('person', 'Cá nhân')], default='company', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=300)),
                ('tax_code', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('requested', 'Chờ xuất'), ('issued', 'Đã xuất'), ('cancelled', 'Đã hủy')], db_index=True, default='requested', max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_request', to='crm.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
