# Generated by Django 5.2.17 on 2026-10-07 08:07

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_order_dossier_submitted_at_order_first_response_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.CharField(default='MSB', max_length=200)),
                ('unit', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('stage', models.CharField(choices=[('shortlisted', 'Đề cử'), ('submitted', 'Đã gửi hồ sơ'), ('interview', 'Phỏng vấn'), ('offer', 'Nhận offer'), ('hired', 'Đã nhận việc'), ('rejected', 'Không đạt'), ('withdrawn', 'Ứng viên rút')], db_index=True, default='shortlisted', max_length=20)),
                ('interview_at', models.DateTimeField(blank=True, null=True)),
                ('interview_location', models.CharField(blank=True, max_length=300)),
                ('feedback', models.TextField(blank=True)),
                ('offer_salary', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('probation_end', models.DateField(blank=True, null=True)),
                ('probation_result', models.CharField(blank=True, choices=[('', 'Chưa đánh giá'), ('passed', 'Qua thử việc'), ('failed', 'Không qua thử việc')], max_length=10)),
                ('guarantee_until', models.DateField(blank=True, null=True)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('left_reason', models.CharField(blank=True, max_length=300)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='crm.order')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='crm.campaignposition')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerShare',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('employer', models.CharField(default='MSB', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('allow_cv', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('placements', models.ManyToManyField(related_name='shares', to='crm.placement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
