# Generated by Django 5.2.17 on 2026-10-02 09:10

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='sepay', max_length=32)),
                ('provider_txn_id', models.CharField(max_length=100)),
                ('gateway', models.CharField(blank=True, max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('transfer_type', models.CharField(blank=True, max_length=10)),
                ('amount', models.BigIntegerField()),
                ('content', models.TextField(blank=True)),
                ('reference_code', models.CharField(blank=True, max_length=100)),
                ('transaction_date', models.CharField(blank=True, max_length=50)),
                ('raw', models.JSONField(default=dict)),
                ('match_status', models.CharField(choices=[('matched', 'Đã khớp'), ('unmatched', 'Chưa khớp'), ('ignored', 'Bỏ qua')], default='unmatched', max_length=20)),
                ('match_note', models.CharField(blank=True, max_length=300)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='crm.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=apps.core.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveBigIntegerField()),
                ('source', models.CharField(choices=[('bank_webhook', 'Webhook ngân hàng'), ('manual', 'Xác nhận thủ công')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('bank_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='payments.banktransaction')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='crm.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_txn_id'), name='uniq_provider_txn'),
        ),
    ]
